### ISSUE TITLE
Error when autocompleting `appearance`

### ISSUE THREAD

**Issue by eric-wood** [Microsoft/vscode-css-languageservice#153]
I get the following error whenever the CSS language service attempts to autocomplete the `appearance` property.

Please let me know if there's any other information I can provide to help!

```[Error - 2:35:04 PM] Error while computing completions for file:///[redacted].scss: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:578879
    at Array.filter (<anonymous>)
    at t.getTermProposals (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:578825)
    at t.e.getCompletionsForDeclarationValue (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:520870)
    at t.e.getCompletionsForExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:530352)
    at t.e.doComplete (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:516088)
    at c.runSafe (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:71319)
    at Immediate.setImmediate [as _onImmediate] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:100717)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)```

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/issues/71715

This fix is available VS Code insiders https://code.visualstudio.com/insiders/, or you can wait until our next release in ~2 weeks.

**Comment by eric-wood** [comment]
Thanks so much!
